version: '3.7'

services:
  app: 
    image: node:14
    container_name: survey-api
    working_dir: /usr/app
    restart: always
    command: bash -c "yarn install --only=prod && yarn debug"
    environment:
      - MONGO_URL=mongodb://root:survey@mongodb:27017/clean-node-api?authSource=admin
    volumes:
      - ./:/usr/app/
    ports:
      - 5050:5050
      - 9222:9222
    depends_on:
      - mongodb
    networks: 
      - survey-network


  mongodb:
    image: mongo:4
    container_name: database-survey
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: survey
    networks: 
      - survey-network

networks: 
    survey-network:
      driver: bridge

volumes: 
  mongodata:
    driver: local