version: '3.3'

services:

  mongo:
    image: mongo:4
    container_name: database_survey
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: survey
    ports:
      - 27017:27017